runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /keybase\.txt
  static_files: keybase.txt
  upload: keybase\.txt

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /about(\.php)?
  script: about.php

- url: /resume(\.php)?
  script: resume.php

- url: /privacypolicy(\.php)?
  script: privacypolicy.php

- url: /termsofuse(\.php)?
  script: termsofuse.php

- url: /sendemail(\.php)?
  script: sendemail.php

- url: /randompicture(\.php)?
  script: randompicture.php

- url: .*
  script: index.php
